spring.application.name=demo

# --- SQL CONFIG ---
spring.datasource.url=jdbc:mysql://localhost:3306/banco?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- MONGODB ---
# Comenta esto si no tienes Mongo corriendo para evitar el error de conexión
# spring.data.mongodb.uri=mongodb://localhost:27017/bank_logs

spring.data.mongodb.repositories.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

# --- LOGGING ---
debug=false
logging.level.org.springframework.data.jpa=INFO

# --- SEGURIDAD ---
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000
server.port=8086
