spring.application.name=demo

# --- CONFIGURACIÓN DE BASE DE DATOS SQL (H2 en memoria) ---
# Esto hace que no necesites MySQL prendido para probar
spring.datasource.url=jdbc:h2:mem:bankdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# --- CONFIGURACIÓN DE MONGODB ---
# Si tienes Docker prendido, usa esta. Si no, comenta estas líneas.
spring.data.mongodb.uri=mongodb://localhost:27017/bank_logs

# --- LOGGING ---
# Mantén el debug en true para que veamos qué pasa si falla
debug=true
logging.level.org.springframework.data.jpa=DEBUG

# --- CONFIGURACIÓN DE SEGURIDAD (JWT) ---
# Esta es la llave secreta para firmar los tokens. 
# Debe ser larga y segura. Puedes usar esta de prueba:
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Tiempo de expiración (ejemplo: 24 horas en milisegundos)
app.jwt.expiration=86400000