package app.domain.enums.sistemRoles;

public enum SistemRole{
    //NATURAL_PERSON,
    //COMPANY,
    NATURAL_CLIENT,
    CLIENT_COMPANY,
    WINDOW_EMPLOYEE,
    COMMERCIAL_EMPLOYEE,
    COMPANY_EMPLOYEE,
    COMPANY_SUPERVISOR,
    INTERNAL_ANALYST
}
